### ISSUE TITLE
Link para API está inativo

### ISSUE THREAD

**Issue by PgPedroGabriel** [cogroo/cogroo4#13]
Preciso utilizar essa versão 4 do cogroo e não tenho acesso a documentação da API pois o link assim descrito no readme.md não está funcionando, gostaria que ou o link ficasse disponviel ou me enviassem por email (se possivel) a documentação
fico muito agradecido, um abraço.

**Comment by dread-uo** [comment]
Oi; chequei o link e está funcionando. O site pode ficar indisponível em alguns horários. Por favor, tente novamente, e veja se consegue agora.

**Comment by PgPedroGabriel** [comment]
Valeu @dread-uo , o link continua inativo por aqui, mas eu verifiquei que em certos horários ele fica ativo, uma dúvida, existe um documento PDF ou DOC para download no caso do link estiver fora eu consultar? Abraço obrigado e parabéns pelo projeto.

**Comment by dread-uo** [comment]
Agradeça ao @wcolen pelo projeto :-)
Até onde eu sei, não há outra documentação da API. Caso precise, pode tentar salvar a wiki da API.

**Comment by wcolen** [comment]
Eu copiei o conteúdo para a wiki do Github. Acho que vamos precisar fazer isso para todo o Wiki que está no Redmine do CCSL :\

**Comment by wcolen** [comment]
https://github.com/cogroo/cogroo4/wiki/API-CoGrOO-4

**Comment by PgPedroGabriel** [comment]
Muito obrigado!

**Comment by michelole** [comment]
A cópia para o Github resolveu o problema.
